spring:
  application:
    name: JavaExperiment
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/loan_calculator?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=utf8mb4
    username: root
    password: xie060106

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sang.javaexperiment.JavaProject4.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

